# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 570ee1f4162921be47dc54c58e1a069e67ec6b5b209b8ea4dc9e558379551d76b04c0b40704eb4699a38acb40646380cd365df619a0566353af105507afa8189

test:
  secret_key_base: 661dcdae644638765e2c6cd44cb094cdc2bccdd68f439505e4ac3e00c04aad0eaa16f7a309bead78f04711d4fee16bf74e006a83a30bcceef0c747b7abf98d47

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
